# Generated by Django 2.2.10 on 2023-02-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
