# Generated by Django 2.2.13 on 2023-02-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inter', '0005_auto_20230205_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='flashcards',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
